### PR TITLE
Switch to use javax.processing for annotation procsssing instead of apt

### PR DESCRIPTION
**Pull request by Cousjava**
This allows for compilation on JDKs > 1.7, as apt was removed in JDK 8

### CODE REVIEW

**Comment by romain-grecourt** [comment]
I'm afraid there is an overlap here. I'm working on similar changes in the 4.1.0-cleanup branch.

**Comment by smillidge** [comment]
@romain-grecourt do you have a PR? Is it worth merging this and then adding any additional changes on top?

**Comment by romain-grecourt** [comment]
The 4.1.0-cleanup has a lot more changes, it's practically not mergeable ; the overlap is unfortunate.
I'm wrapping up my work, it should ready to be merged back to master sometime next week.

**Comment by smillidge** [comment]
OK let's do it the other way around you merge yours then we review this.

**Comment by romain-grecourt** [comment]
@smillidge I've merged my changes. Please take a look at the master branch.
Note that I've renamed the modules so the code in this PR will be hard to merge with the changes that I made.

**Pull request closed without merging**
