### PR TITLE
Record position of 5.0.0.RC1 branch

### PR DESCRIPTION
**Pull request by pzygielo**

### CODE REVIEW

**Comment by dmatej** [comment]
If the branch is deleted, what is the purpose of these PRs?
I see just these tags: https://github.com/eclipse-ee4j/glassfish-woodstock/tags

**Comment by pzygielo** [comment]
To not lost the `Prepare next development cycle for ...` commits, should they be needed for some reason in the future.

**Comment by pzygielo** [comment]
Given many branches were kept for 2 or 3 years, they looked like very needed for something.

**Comment by dmatej** [comment]
> To not lost the `Prepare next development cycle for ...` commits, should they be needed for some reason in the future.

Aha, so the only purpose is to have this diff here on GitHub? Deleted branches won't be in any clone of the repo, just tags (which is usually enough).  I am not sure if it is enough, but while it is just about these changes, ok ...

**Comment by pzygielo** [comment]
> Aha, so the only purpose is to have

My intention is to have _Restore branch_ button. In other words - to delete the branch, but have the way to restore it easily, without using other fork (which at the required time might be none).
The tag points to the commit-before.

**Comment by dmatej** [comment]
Hmm, on one hand I see it as an antipattern, on the other ... well, if we take it as a part of THE lifecycle, that at some point in time we drop unsupported branches, but we still keep some track of them somewhere ... Ok, that's a good idea :-)

**Pull request closed without merging**
